COMP307FinalProject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from user_app import views as user_views
from django.contrib.auth import views as auth_views



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('user/',include('user_app.urls')),
    path('auction/',include('auction.urls'))

]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path

from . import views

app_name = 'main'
urlpatterns = [
    path('', views.index, name='index'),
    path('review-order/', views.review_order, name='review_order'),
    path('checkout/', views.checkout, name='checkout'),
    path('place-order/', views.place_order, name='place_order'),
    path('order-success/', views.order_success, name='order_success'),
    path('payment/',views.PaymentView.as_view(), name= 'payment')
]

main/models.py
from django.db import models

# Create your models here.

main/views.py
# Create your views here.
from django.shortcuts import render, get_object_or_404
from django.db import transaction
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseBadRequest, JsonResponse
from django.urls import reverse_lazy

from auction.forms import PlaceOrderForm
from auction.models import Product, Order, Cart, Inventory
import json
from django.views.generic.base import TemplateView
from django.conf import settings

def _transform_product_list(products: list):
    return list(map(lambda x: {
            "title": x.title,
            "price": x.price,
            "description": x.description,
            "link": f"/auction/{x.id}",
            "image": x.image.url,
            "created_at": x.created_at
        }, products))


def index(request):
    trending_product_list = Product.objects.all()
    # Get the latest 5 products
    latest_product_list = Product.objects.order_by('-created_at')[:4]

    # ! Important: Use {{ ... |safe}} to prevent character escape in the template
    context = {
        'trending_products': _transform_product_list(trending_product_list),
        'latest_products': _transform_product_list(latest_product_list),
    }
    return render(request, 'main/index.html', context)


def review_order(request):
    try:
        cart = Cart.objects.get(user=request.user)
    except Cart.DoesNotExist:
        cart = Cart()
        cart.user = request.user
    cart_items = json.loads(cart.items) if cart.items else {}

    shown_list = []
    total_price = total_amount = 0
    for item_id, amount in cart_items.items():
        try:
            product = Product.objects.get(pk=int(item_id))
            if int(amount) > 0:
                subtotal = round(float(product.price) * int(amount), 2)
                to_append = {
                    'id': product.id,
                    'title': product.title,
                    'amount': amount,
                    'subtotal': "{:.2f}".format(subtotal),
                }
                total_price += subtotal
                total_amount += int(amount)

                # Check stock left, this handles out of stock items
                try:
                    inventory = Inventory.objects.get(item=product)
                    to_append.update({
                        'stock_left': inventory.stock_count
                    })
                except Inventory.DoesNotExist:
                    to_append.update({
                        'stock_left': 0
                    })

                shown_list.append(to_append)
        except Product.DoesNotExist:
            continue

    return render(request, 'main/review_order.html', {
        'cart': shown_list,
        'total_price': "{:.2f}".format(total_price),
        'total_amount': total_amount,
    })


def checkout(request):
    try:
        Cart.objects.get(user=request.user)
    except Cart.DoesNotExist:
        return HttpResponseBadRequest

    shipping_address = request.user.profile.shipping_address
    return render(request, 'main/checkout.html', {'shipping_address': shipping_address})

ttl_price = 0
def place_order(request):
    if request.method == 'POST':
        form = PlaceOrderForm(request.POST)
        if form.is_valid():
            cart = get_object_or_404(Cart, user=request.user)
            # Make sure we don't place an order with an empty cart
            if cart.items == "":
                raise HttpResponseBadRequest

            cart_items = json.loads(cart.items)
            order_items = []
            total_amount = total_price = 0
            # same exception handling as above
            if len(cart_items) < 1:
                raise HttpResponseBadRequest

            with transaction.atomic():
                for item_id, amount in cart_items.items():
                    product = get_object_or_404(Product, pk=int(item_id))
                    product_ivt = get_object_or_404(Inventory, item=int(item_id))
                    if product_ivt.stock_count - int(amount) < 0:
                        # Prevent transaction from committing if there's not enough stock
                        transaction.rollback()
                        # Go back to review order
                        return HttpResponseRedirect('/review-order/')
                    else:
                        product_ivt.stock_count -= int(amount)
                        product_ivt.save()

                        price = round(float(product.price) * int(amount), 2)
                        order_items.append({
                            'id': item_id,
                            'title': product.title,
                            'amount': amount,
                            'subtotal': price
                        })
                        total_amount += int(amount)
                        total_price += price

            # Save new order
            order = Order()
            order.user = request.user
            order.items = json.dumps(order_items)
            order.total_price = total_price
            ttl_price = total_price
            order.total_amount = total_amount
            order.shipping_address = form.cleaned_data['shipping_address']
            order.save()

            # Clear cart
            cart.items = json.dumps({})
            cart.save()

            # Save shipping address if requested
            print(request.POST)
            if request.POST.get('remember_address', False):
                profile = request.user.profile
                profile.shipping_address = form.cleaned_data['shipping_address']
                profile.save()

            #return HttpResponseRedirect('/order-success/')
            return HttpResponseRedirect('/payment/')

    return HttpResponseRedirect('/checkout/')



class PaymentView(TemplateView):
    template_name = 'main/payment.html'

    def get_context_data(self, **kwargs): # new
        context = super().get_context_data(**kwargs)
        context['key'] = settings.STRIPE_PUBLISHABLE_KEY
        context['price'] = 0
        return context


def order_success(request):
    return render(request, 'main/order_success.html')

main/templates/main/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Load required Bootstrap and BootstrapVue CSS -->
    <link type="text/css" rel="stylesheet" href="//unpkg.com/bootstrap/dist/css/bootstrap.min.css" />
    <link type="text/css" rel="stylesheet" href="//unpkg.com/bootstrap-vue@latest/dist/bootstrap-vue.min.css" />
    <link type="text/css" rel="stylesheet" href="https://cdn.materialdesignicons.com/5.0.45/css/materialdesignicons.min.css" />
    {% load static %}
    <link type="text/css" rel="stylesheet" href="{% static 'main/app.css' %}" />
    <!-- Load polyfills to support older browsers -->
    <script src="//polyfill.io/v3/polyfill.min.js?features=es2015%2CArray.from%2CArray.isArray%2CObject.assign%2CObject.is%2CPromise%2CMutationObserver%2CIntersectionObserver"></script>
    <!-- Load Vue followed by BootstrapVue -->
    <!--<script src="//unpkg.com/vue@latest/dist/vue.min.js"></script>-->
    <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
    <script src="//unpkg.com/bootstrap-vue@latest/dist/bootstrap-vue.min.js"></script>
    <!-- Load the following for BootstrapVueIcons support -->
    <script src="//unpkg.com/bootstrap-vue@latest/dist/bootstrap-vue-icons.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>

    <title>{% block title %}Marketplace{% endblock %}</title>
    {% block header %}
    {% endblock %}
</head>
<body>
    <div id="app">
        <b-navbar type="dark" variant="dark">
            {% block navbar %}
            <b-navbar-brand href="/">Marketplace</b-navbar-brand>
            <b-navbar-nav>
                <!-- add more navs here -->
            </b-navbar-nav>

            <b-navbar-nav class="ml-auto">
                {% if user.is_authenticated %}
                    <b-button variant="info" href="/review-order/" class="mr-3">
                        <span class="mdi mdi-cart mr-2"></span>Cart ({{cart_item_count}})
                    </b-button>
                    <b-nav-item-dropdown text="{{ user.username }}" right>
                        <b-dropdown-item href="/user/profile">Account</b-dropdown-item>
                        <b-dropdown-item href="#">Settings</b-dropdown-item>
                        <b-dropdown-item href="/user/logout">Logout</b-dropdown-item>
                    </b-nav-item-dropdown>
                {% else %}
                    <b-nav-item href="/user/login">Login</b-nav-item>
                {% endif %}
            </b-navbar-nav>
            {% endblock %}
        </b-navbar>
        <b-container class="mt-3 mb-5">
            {% block content %}{% endblock %}
        </b-container>
    </div>
</body>

<script type="text/javascript">
    {% block js %}
    {% endblock %}
    Vue.config.devtools = true;

    var pageMixin = {
        {% block vue %}
        data: {
        },
        {% endblock %}
    };

    var app = new Vue({
        delimiters: ['[[', ']]'],
        el: '#app',
        mixins: [pageMixin],
        data() {
            return {
            };
        },
    });
</script>
</html>

main/templates/main/checkout.html
{% extends "main/base.html" %}

{% block content %}
    <b-row>
        <b-col>
            <h1>Checkout</h1>
        </b-col>
    </b-row>
        <b-form method="POST" action="/place-order/">
            {% csrf_token %}
            <b-form-group
                label="Shipping address:"
                label-for="shipping-address"
            >
                <b-form-textarea
                    id="shipping-address"
                    name="shipping_address"
                    v-model="form.address"
                    :state="addressState"
                    required
                    rows="5"
                    no-resize
                    placeholder="Ex. 845 Sherbrooke St W, Montreal, Quebec H3A 0G4, Canada"
                ></b-form-textarea>
                <b-form-invalid-feedback :state="addressState">
                    Please fill in your address.
                </b-form-invalid-feedback>
            </b-form-group>
            <b-form-checkbox
              id="remember-checkbox"
              name="remember_address"
              v-model="form.rememberAddr"
            >
              Remember shipping address
            </b-form-checkbox>

            <b-row align-h="end">
                <b-col cols="auto">
                    <b-button variant="success" :disabled="!addressState" type="submit">
                        Place order
                    </b-button>
                </b-col>
            </b-row>
        </b-form>
    <b-row>

    </b-row>
{% endblock %}

{% block vue %}
    data() {
        return {
            form: {
                address: "{{shipping_address}}",
                rememberAddr: true,
            },
        };
    },
    computed: {
        addressState() {
            if (this.form.address) return true;
            return false;
        },
    },
{% endblock %}

main/templates/main/index.html
{% extends "main/base.html" %}
{% block content %}
    <b-row class="mb-2 mx-0">
        <h3>New</h3>
    </b-row>
    <b-row class="mb-5">
        {% for item in latest_products %}
        <b-col cols="6" md="4" lg="3" class="mb-3">
            <b-card
                title="{{ item.title }}"
                sub-title="$ {{ item.price }}"
                img-src="{{ item.image }}"
                img-alt="{{ item.title }}-img"
                class="product-card latest"
            >
                <b-card-text>
                  {{ item.description }}
                </b-card-text>
                {% if user.is_authenticated %}
                <b-button href="{{ item.link }}" variant="primary">
                    Check it out
                </b-button>
                {% else %}
                    <b-button href="{% url 'login' %}" variant="primary">
                    Check it out
                </b-button>
                {% endif %}

                <template v-slot:footer>
                    <small class="text-muted">Added on {{ item.created_at }}</small>
                </template>
            </b-card>
        </b-col>
        {% endfor %}
    </b-row>
    <b-row class="pt-2 mb-2 mx-0">
        <h2>All listings</h2>
    </b-row>
    <b-row class="mb-5" align-v="start">
        {% for item in trending_products %}
        <b-col cols="6" md="4" lg="3" class="mb-3 h-100">
            <b-card
                title="{{ item.title }}"
                sub-title="$ {{ item.price }}"
                img-src="{{ item.image }}"
                img-alt="{{ item.title }}-img"
                class="product-card"
            >
                <b-card-text>
                  {{ item.description }}
                </b-card-text>

                <b-button href="{{ item.link }}" variant="primary">
                    Check it out
                </b-button>
            </b-card>
        </b-col>
        {% endfor %}
    </b-row>
{% endblock %}

main/templates/main/order_success.html
{% extends "main/base.html" %}

{% block content %}
    <b-row class="my-5" align-h="center">
        <b-col cols="auto">
            <h3>Your order has been placed.</h3>
        </b-col>
    </b-row>
    <b-row align-h="center">
        <b-col cols="auto">
            <b-button href="/">Back to Homepage</b-button>
        </b-col>
        <b-col cols="auto">
            <b-button href="/user/profile/orders">View Order History</b-button>
        </b-col>
    </b-row>
{% endblock %}

main/templates/main/payment.html
<form action="{% url 'main:order_success' %}" method="post">
    {% csrf_token %}
    <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
        data-key="{{ key }}"
        data-description="A Django Charge"
        data-amount="{{ price }}"
        data-locale="auto">
    </script>
</form>

main/templates/main/review_order.html
{% extends "main/base.html" %}

{% block content %}
    <b-row class="mb-4">
        <b-col>
            <h1>Your shopping cart</h1>
        </b-col>
    </b-row>
    <template v-if="cart.length > 0">
        <b-row class="mb-4">
            <b-col>
                <b-table-simple>
                    <b-thead>
                        <b-tr>
                            <b-th>Item name</b-th>
                            <b-th>Quantity</b-th>
                            <b-th>Subtotal</b-th>
                            <b-th></b-th>
                        </b-tr>
                    </b-thead>
                    <b-tbody>
                        <b-tr v-for="(entry, i) in cart" :key="i" :variant="rowVariant(entry)">
                            <b-td cols="auto" class="text-truncate font-weight-bold">
                                <span
                                        v-if="itemHasStockError(entry)"
                                        v-b-tooltip.hover :title="stockErrorTooltip(entry)"
                                        class="mdi mdi-alert mr-2"
                                ></span>
                                [[ entry.title ]]
                            </b-td>
                            <b-td>
                                [[ entry.amount ]]
                            </b-td>
                            <b-td>
                                $ [[ entry.subtotal ]]
                            </b-td>
                            <b-td>
                                <b-button variant="danger" pill @click="removeCartItem(entry.id)">
                                    <span class="mdi mdi-delete"></span> Delete
                                </b-button>
                            </b-td>
                        </b-tr>
                    </b-tbody>
                    <b-tfoot>
                        <b-tr variant="secondary">
                            <b-td></b-td>
                            <b-td class="font-weight-bold">{{ total_amount }}</b-td>
                            <b-td class="font-weight-bold" style="color:#30bf48">
                                $ {{ total_price }}
                            </b-td>
                            <b-th class="text-muted">Total</b-th>
                        </b-tr>
                    </b-tfoot>
                </b-table-simple>
            </b-col>
        </b-row>
        <b-row align-h="end">
            <b-col cols="auto">
                <b-button variant="success" href="/checkout/" :disabled="cartHasStockError">
                    Proceed to checkout
                </b-button>
            </b-col>
        </b-row>
    </template>
    <b-row v-else>
        <b-col>
            <p class="my-4">Your cart is empty.</p>
        </b-col>
    </b-row>
    {% csrf_token %}
{% endblock %}

{% block vue %}
    data() {
        return {
            cart: {{cart|safe}}
        };
    },
    computed: {
        cartHasStockError() {
            return this.cart.some(item => this.itemHasStockError(item))
        },
    },
    methods: {
        removeCartItem(id) {
            const csrfToken = document.getElementsByName('csrfmiddlewaretoken')[0].value;
            axios.post('/auction/remove-from-cart/', {
                itemId: id,
            }, {
                headers: {
                    'X-CSRFToken': csrfToken
                },
            }).then(() => {
                window.location.reload();
            });
        },
        itemHasStockError(item) {
            return Number(item.stock_left) < Number(item.amount);
        },
        rowVariant(item) {
            if (this.itemHasStockError(item)) return 'warning';
            return null;
        },
        stockErrorTooltip(item) {
            if (item.stock_left < 1) return 'No stock left!'
            return `Only ${item.stock_left} items remaining!`;
        },
    },
{% endblock %}