COMP307FinalProject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from user_app import views as user_views
from django.contrib.auth import views as auth_views



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('user/',include('user_app.urls')),
    path('auction/',include('auction.urls'))

]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

auction/urls.py
from django.urls import path

from . import views


app_name = 'auction'
urlpatterns = [
    path('<int:item_id>/', views.detail, name='detail'),
    path('create/', views.create, name='create'),
    path('<int:item_id>/add-to-cart/', views.add_prod_to_cart, name='add_prod_to_cart'),
    path('remove-from-cart/', views.remove_prod_from_cart, name='remove_prod_from_cart'),
    path('<int:item_id>/restock/', views.restock, name='restock'),
    path('<int:item_id>/info/', views.product_info, name='product_info'),
    path('<int:item_id>/delete/', views.delete_product, name='delete'),
]

main/urls.py
from django.urls import path

from . import views

app_name = 'main'
urlpatterns = [
    path('', views.index, name='index'),
    path('review-order/', views.review_order, name='review_order'),
    path('checkout/', views.checkout, name='checkout'),
    path('place-order/', views.place_order, name='place_order'),
    path('order-success/', views.order_success, name='order_success'),
    path('payment/',views.PaymentView.as_view(), name= 'payment')
]

auction/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
from django.contrib.auth.models import User
import time
import os
# Create your models here.


def product_imagepath(instance, filename):
    # file will be uploaded to MEDIA_ROOT/product_pics/user_<id>/<generated filename>
    parts = os.path.splitext(filename)
    ext = parts[1].lower() if len(parts) > 1 else ''
    return 'product_pics/user_{0}/{1}'.format(instance.user.id, f"{int(time.time())}{ext}")


class Product(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    price = models.DecimalField(default=0, decimal_places=2, max_digits=10)
    description = models.CharField(max_length=200)
    image = models.ImageField(default='product_pics/default_product_pic.png', upload_to=product_imagepath)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title


class Cart(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    items = models.TextField(blank=True)  # use json.dumps to stringify the list of items

    def __str__(self):
        return str(self.user) + " Cart"


class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    items = models.TextField()  # use json.dumps to stringify the list of items
    total_amount = models.IntegerField(validators=[MinValueValidator(1)])
    total_price = models.FloatField(validators=[MinValueValidator(0.0)])
    shipping_address = models.TextField()
    time_placed = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user}'s order at {self.time_placed}"


class Inventory(models.Model):
    item = models.OneToOneField(Product, on_delete=models.CASCADE)
    stock_count = models.IntegerField(default=1, validators=[MinValueValidator(0)])

    def __str__(self):
        return str(self.item) + " Inventory"

    def in_stock(self):
        if self.stock_count <= 0:
            return False
        return True

auction/forms.py
from django import forms
from django.db import models
from auction.models import Product, Order


class CreateForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['title', 'price', 'description', 'image']


class UpdateForm(forms.ModelForm):
    image = forms.ImageField(required=False)

    class Meta:
        model = Product
        fields = ['title', 'price', 'description', 'image']


class PlaceOrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['shipping_address']

auction/views.py
from django.shortcuts import render, get_object_or_404
# Create your views here.
from django.db import transaction
from auction.forms import CreateForm, UpdateForm
from auction.models import Product, Inventory, Cart
from user_app.models import User
from django.http import JsonResponse, HttpResponse, HttpResponseRedirect, \
    HttpResponseBadRequest, HttpResponseForbidden, HttpResponseNotFound
import json


def detail(request, item_id):
    product = get_object_or_404(Product, pk=item_id)
    try:
        ivt = Inventory.objects.get(item=product)
    except Inventory.DoesNotExist:
        ivt = Inventory()
        ivt.item = product
        ivt.save()
    stock_count = ivt.stock_count
    seller = User.objects.get(pk=product.user.id)

    # Deduct stock count if the item is in cart
    try:
        cart = Cart.objects.get(user=request.user)
        cart_items = json.loads(cart.items)
        in_cart_item_count = int(cart_items[str(item_id)]) if str(item_id) in cart_items else 0
    except Cart.DoesNotExist:
        in_cart_item_count = 0

    return render(request, 'auction/product_details.html', {
        'product': product,
        'stock_count': stock_count,
        'in_cart': in_cart_item_count,
        'stock_left': stock_count - in_cart_item_count,
        'seller': seller,
        'pid': product.id,
        'username': request.user.username,
    })


def restock(request, item_id):
    if request.method == 'POST':
        # check if product exist
        try:
            product = Product.objects.get(pk=item_id)
        except Product.DoesNotExist:
            raise HttpResponseNotFound

        # get values from request body
        try:
            body = json.loads(request.body)
            amount = body['amount']
        except ValueError:
            raise HttpResponseBadRequest

        # check if the user is authorized to restock
        if product.user != request.user:
            raise HttpResponseForbidden

        try:
            inventory = Inventory.objects.get(item=item_id)
        except Inventory.DoesNotExist:
            inventory = Inventory()
            inventory.item = item_id

        inventory.stock_count += amount
        inventory.save()
        return HttpResponse('Restocked.')


def create(request):
    if request.method == 'POST':
        form = CreateForm(request.POST, request.FILES)
        if form.is_valid():
            # create new product entry
            prod = form.save(commit=False)
            prod.user = request.user
            prod.save()

            # create new inventory entry associated with this product
            ivt = Inventory()
            ivt.item = prod
            ivt.save()

            return HttpResponse('Item added.')
        else:
            response = JsonResponse({'errors': form.errors})
            response.status_code = 400
            return response


def product_info(request, item_id):
    """
    Used to fetch the product's data for the update operation
    """
    product = get_object_or_404(Product, pk=item_id)
    if request.method == 'GET':
        return JsonResponse({
            'product': {
                'title': product.title,
                'price': product.price,
                'description': product.description,
            }
        })
    elif request.method == 'POST':
        form = UpdateForm(request.POST, request.FILES)
        if form.is_valid():
            product.title = form.cleaned_data['title']
            product.price = form.cleaned_data['price']
            product.description = form.cleaned_data['description']

            # Optionally update the product's image
            if form.cleaned_data.get('image'):
                product.image = form.cleaned_data['image']

            product.save()
            return HttpResponse('Item information updated.')
        else:
            response = JsonResponse({'errors': form.errors})
            response.status_code = 400
            return response


def delete_product(request, item_id):
    if request.method == 'POST':
        product = get_object_or_404(Product, pk=item_id)
        # Prevent users other than the seller to remove this product
        if product.user != request.user:
            return HttpResponseForbidden
        product.delete()
        return HttpResponse('Item deleted.')


def add_prod_to_cart(request, item_id):
    if request.method == 'POST':
        try:
            cart = Cart.objects.get(user=request.user)
        except Cart.DoesNotExist:
            cart = Cart()
            cart.user = request.user
            cart.items = ""

        # Make sure we don't add out of stock items
        inventory = get_object_or_404(Inventory, item=int(item_id))
        if inventory.stock_count < 1:
            raise HttpResponseBadRequest

        if cart.items == "":
            items = {}
        else:
            items = json.loads(cart.items)

        amount = int(request.POST.get('amount', 1))
        if str(item_id) in items:
            amount += int(items[str(item_id)])

        items[str(item_id)] = amount

        cart.items = json.dumps(items)
        cart.save()

    return HttpResponseRedirect(f"/auction/{item_id}")


def remove_prod_from_cart(request):
    if request.method == 'POST':
        cart = get_object_or_404(Cart, user=request.user)

        try:
            body = json.loads(request.body)
            item_id = body['itemId']
        except ValueError:
            raise HttpResponseBadRequest

        cart_items = json.loads(cart.items)
        # Remove item entirely from cart
        cart_items.pop(str(item_id))
        cart.items = json.dumps(cart_items)
        cart.save()

        return HttpResponse(f"Item {item_id} removed from cart.")

auction/templates/auction/product_details.html
{% extends "main/base.html" %}
{% load static %}

{% block header %}
    <link type="text/css" rel="stylesheet" href="{% static 'auction/styles.css' %}" />
{% endblock %}

{% block content %}
    <b-row align-h="center" class="mb-5">
        <b-col class="product-image-container" cols="auto">
            <b-img src="{{ product.image.url }}" fluid alt="{{ product.title }}-img"></b-img>
        </b-col>
    </b-row>
    <b-row class="mt-2 mb-4">
        <b-col class="pr-5">
            <h1>{{ product.title }}</h1>
            <span class="font-weight-bold" style="color:#30bf48">${{product.price}}</span>
            <p class="mt-3">{{product.description}}</p>
        </b-col>
        <b-col cols="auto">
            <b-row class="mb-4">
                <b-col>
                    <b-row align-h="center" class="mb-3">
                        <b-avatar variant="info" src="{{ seller.profile.image.url }}" size="8rem"></b-avatar>
                    </b-row>
                    <b-row align-h="center">
                        <p class="text-muted">Seller: {{ seller.username }}</p>
                    </b-row>
                </b-col>
            </b-row>
            <b-row>
                <b-col>
                    {% if seller == user %}
                        <b-row align-h="center" class="mb-2">
                            <b-button @click="openRestockForm({{ product.id }})" variant="primary">
                                Restock
                            </b-button>
                            <restock-form ref="restockForm" item-name="{{ product.title }}"></restock-form>
                        </b-row>
                    {% else %}
                        <b-row align-h="center" class="mb-2">
                            <b-form method="post" action="{% url 'auction:add_prod_to_cart' product.id %}">
                                {% csrf_token %}
                                {% if stock_count > 0 %}
                                    <b-form-spinbutton
                                            name="amount" class="mb-3"
                                            min="1" max="{{ stock_left }}"
                                            :value="1"
                                            {% if stock_left <= 0 %} disabled {% endif %}
                                    ></b-form-spinbutton>
                                {% endif %}
                                <b-button
                                    {% if stock_count > 1 %} variant="primary" {% endif %}
                                    {% if stock_count < 1 or stock_left <= 0 %} disabled {% endif %}
                                    type="submit"
                                >
                                    <span class="mdi mdi-cart mr-2"></span> Add to Cart
                                </b-button>
                            </b-form>
                        </b-row>
                    {% endif %}
                    <b-row align-h="center">
                        {% if stock_count > 5 %}
                            <span class="text-success">In stock</span>
                        {% elif stock_count > 0 %}
                            <span class="text-warning">{{ stock_count }} items left!</span>
                        {% else %}
                            <span class="text-danger">Out of stock</span>
                        {% endif %}

                        {% if in_cart > 0 %}
                            <span class="text-muted ml-2">({{ in_cart }} in cart)</span>
                        {% endif %}
                    </b-row>
                </b-col>
            </b-row>
        </b-col>
    </b-row>

    <div id="chatroom-tab" @click="displayChat = true">
        <span class="mdi mdi-forum mr-2"></span>Chat with seller
    </div>
    <div id="chatroom">
        <b-container fluid class="h-100">
            <b-row align-h="between" class="my-3">
                <b-col cols="auto">
                    <span class="font-weight-bold text-white">Chat with seller</span>
                </b-col>
                <b-col cols="auto">
                    <span id="close-btn" class="mdi mdi-close" @click="displayChat = false"></span>
                </b-col>
            </b-row>
            <b-row>
                <b-col cols="12" id="chat-log__container">
                    <div id="chat-log">
                        <span v-for="(msg, i) in chat.log" :key="i"
                              class="mb-2"
                              :class="{'self-msg': msg.username === chat.username}"
                        >
                            <strong v-if="msg.username === chat.username" class="mr-1">You:</strong>
                            <strong v-else class="mr-1">[[ msg.username ]]:</strong>
                            [[ msg.message ]]
                        </span>
                    </div>
                </b-col>
            </b-row>
            <b-row class="my-3">
                <b-col>
                    <b-form autocomplete="off" @submit.prevent="sendMessage">
                        <b-form-row>
                            <b-col>
                                <b-form-input v-model="chat.input" type="text" size="10"></b-form-input>
                            </b-col>
                            <b-col cols="auto">
                                <b-button type="submit" variant="primary">Send</b-button>
                            </b-col>
                        </b-form-row>
                    </b-form>
                </b-col>
            </b-row>
        </b-container>
    </div>
{% endblock %}

{% block js %}
    {% if seller == user %}
        {% include "auction/restock_form.js" %}
    {% endif %}
{% endblock %}

{% block vue %}
    data: {
        displayChat: false,
        chat: {
            username: "{{user.username}}",
            socket: null,
            input: '',
            log: [],
        },
    },
    watch: {
        displayChat(shouldDisplay) {
            if (shouldDisplay) {
                document.getElementById('chatroom').classList.add('active');
            } else {
                document.getElementById('chatroom').classList.remove('active');
            }
        },
    },
    created() {
        const pid = {{ pid }};

        const chatSocket = new WebSocket(
            'ws://'
            + window.location.host
            + '/ws/auction/'
            + pid
            + '/'
        );
        const g = this;
        chatSocket.onmessage = function(e) {
            const data = JSON.parse(e.data);
            g.chat.log.unshift(data.message);
        };
        chatSocket.onclose = function(e) {
            console.error('Chat socket closed unexpectedly');
        };
        this.chat.socket = chatSocket;
    },
    destroyed() {
        this.chat.socket.close();
        this.chat.socket = null;
    },
    methods: {
        openRestockForm(id) {
            this.$refs.restockForm.openRestockForm(id);
        },
        sendMessage() {
            this.chat.socket.send(JSON.stringify({
                username: this.chat.username,
                message: this.chat.input,
            }));
            this.chat.input = '';
        },
    },
{% endblock %}